import { WorkspaceFrame } from "@/components/WorkspaceFrame";
import { Check } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { useState } from "react";
import { toast } from "sonner";

export default function Billing() {
  const [interval, setInterval] = useState<"month" | "year">("month");
  const plans = [["pro", "Pro", "$29", "$290", "For independent owners who need a focused growth loop."], ["growth", "Growth", "$79", "$790", "For growing teams that need deeper scans and more frequent intelligence."]] as const;
  const { data: billing } = trpc.billing.status.useQuery();
  const checkout = trpc.billing.checkout.useMutation({ onSuccess: ({ checkoutUrl }) => { toast.success("Opening secure Stripe Checkout in a new tab"); window.open(checkoutUrl, "_blank", "noopener,noreferrer"); }, onError: error => toast.error(error.message) });
  const portal = trpc.billing.portal.useMutation({ onSuccess: ({ portalUrl }) => window.open(portalUrl, "_blank", "noopener,noreferrer"), onError: error => toast.error(error.message) });
  const accessLabel = billing?.accessSource === "owner" ? "Founder Mode · full access" : billing?.accessSource === "beta" ? "Founding Beta · seven-day access" : billing?.accessSource === "stripe" ? `${billing.status === "trialing" ? "Trial" : "Subscription"} · ${billing.plan || "Cresna"}` : "No active trial or subscription";
  const periodLabel = billing?.currentPeriodEnd ? `${billing.accessSource === "beta" ? "Beta access ends" : billing.status === "trialing" ? "Trial ends" : "Renews"} ${new Date(billing.currentPeriodEnd).toLocaleDateString()}` : null;
  return <WorkspaceFrame eyebrow="Billing" title="Choose the rhythm that fits your team." description="Every new subscription begins with a 14-day full-access trial. Checkout and subscription changes are handled securely by Stripe."><div className="mb-7 flex flex-col items-start gap-4 border-b border-[#17201e]/10 pb-6 sm:flex-row sm:items-center sm:justify-between"><div className="rounded-full border border-[#17201e]/15 bg-[#fdfdfb] p-1"><button type="button" onClick={() => setInterval("month")} className={`rounded-full px-3 py-2 text-[11px] font-bold ${interval === "month" ? "bg-[#17201e] text-[#f8f7f2]" : "text-[#65706b]"}`}>Monthly</button><button type="button" onClick={() => setInterval("year")} className={`rounded-full px-3 py-2 text-[11px] font-bold ${interval === "year" ? "bg-[#17201e] text-[#f8f7f2]" : "text-[#65706b]"}`}>Annual · 2 months free</button></div><div className="text-left sm:text-right"><p className="text-[11px] font-bold text-[#17201e]">{accessLabel}</p>{periodLabel ? <p className="mt-1 text-[11px] text-[#65706b]">{periodLabel}</p> : null}{billing?.accessSource === "stripe" ? <button type="button" onClick={() => portal.mutate()} disabled={portal.isPending} className="mt-2 text-[11px] font-bold text-[#17201e] underline underline-offset-4 disabled:opacity-60">Manage subscription</button> : null}</div></div><div className="grid gap-5 lg:grid-cols-2">{plans.map(([key, name, monthly, annual, note], index) => <article key={name} className={`rounded-[1.35rem] border p-7 ${index ? "border-[#17201e] bg-[#17201e] text-[#f8f7f2]" : "border-[#17201e]/12 bg-[#fdfdfb]"}`}><p className={`eyebrow text-[10px] ${index ? "text-[#d9fa55]" : "text-[#65706b]"}`}>{name}</p><p className="mt-5 text-5xl font-extrabold tracking-[-0.07em]">{interval === "month" ? monthly : annual}</p><p className={`mt-2 text-xs ${index ? "text-[#b6c1bb]" : "text-[#65706b]"}`}>{interval === "month" ? "per month" : "per year"}</p><p className={`mt-7 text-sm leading-6 ${index ? "text-[#d9e1dc]" : "text-[#53605a]"}`}>{note}</p><div className={`mt-7 flex items-center gap-2 text-xs font-bold ${index ? "text-[#f8f7f2]" : "text-[#17201e]"}`}><Check className={`h-4 w-4 ${index ? "text-[#d9fa55]" : "text-[#7c9b1e]"}`} /> 14-day full-access trial</div><button type="button" onClick={() => checkout.mutate({ plan: key, interval })} disabled={checkout.isPending || billing?.hasAccess} className={`mt-9 h-11 w-full rounded-full text-xs font-bold ${index ? "bg-[#d9fa55] text-[#17201e] hover:bg-[#e4ff83]" : "bg-[#17201e] text-[#f8f7f2] hover:bg-[#293630]"} disabled:opacity-60`}>{billing?.hasAccess ? "Current access is active" : checkout.isPending ? "Creating Checkout…" : "Start 14-day trial"}</button></article>)}</div></WorkspaceFrame>;
}
