import { EmptyWorkspaceCard, WorkspaceFrame } from "@/components/WorkspaceFrame";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { AlertCircle, BarChart3, FilePenLine, FileText, Landmark, Loader2, Package, ReceiptText, TrendingUp, UsersRound } from "lucide-react";
import type { ComponentType } from "react";
import { useLocation } from "wouter";

export type CommerceSection = "orders" | "drafts" | "shipping" | "products" | "customers" | "growth" | "discounts" | "content" | "markets" | "finance" | "analytics";
type Metric = { id: number; metricDate: Date; orderCount: number; customerCount: number; checkoutCount: number; abandonedCheckoutCount: number; refundCount: number; netRevenue: string | number };
type Score = { overallScore?: number | null; coveragePercent?: number; status?: string };
type Product = { id: number; title: string; descriptionHtml: string | null; seoTitle: string | null; seoDescription: string | null; mediaCount: number | null };
type Draft = { draft: { id: number; actionType: string; status: string }; product: { title: string } | null };

const unavailable = new Set<CommerceSection>(["shipping", "discounts", "markets"]);
const copy: Record<CommerceSection, { eyebrow: string; title: string; description: string; blocked?: string; action?: string; actionLabel?: string }> = {
  orders: { eyebrow: "Order intelligence", title: "Read order patterns, not a copied order inbox.", description: "Cresna turns approved Shopify syncs into aggregate order, checkout, revenue, and refund evidence. Fulfillment and individual orders remain in Shopify Admin." },
  drafts: { eyebrow: "Draft review", title: "Review before anything can change.", description: "Cresna keeps product and positioning drafts in a merchant-controlled queue. Approval records your decision; it does not publish to Shopify.", action: "/app/ai-studio", actionLabel: "Open AI Action Studio" },
  shipping: { eyebrow: "Shipping labels", title: "Shipping labels are not connected yet.", description: "Cresna does not currently create, buy, or manage shipping labels. That requires a dedicated fulfillment integration and explicit write permissions.", blocked: "No shipping-label integration or fulfillment write scope is configured." },
  products: { eyebrow: "Catalog intelligence", title: "Spot catalog gaps in the records Cresna can verify.", description: "Catalog quality signals use connected product fields. Product writing remains a reviewable draft until a merchant-approved write integration exists.", action: "/app/ai-studio", actionLabel: "Create a reviewable draft" },
  customers: { eyebrow: "Customer signals", title: "See aggregate demand signals without exposing people.", description: "Cresna uses approved aggregate customer reporting for directional demand evidence. It does not expose profiles, segments, support history, or outreach tools." },
  growth: { eyebrow: "Growth operating system", title: "Move from store evidence to a measured next step.", description: "Growth combines business context, connected evidence, ranked opportunities, reviewable drafts, and outcome tracking.", action: "/app/actions", actionLabel: "Review opportunities" },
  discounts: { eyebrow: "Discounts", title: "Discount creation is not connected yet.", description: "Cresna can surface pricing evidence, but it does not create Shopify discounts without discount write scopes and an explicit merchant approval flow.", blocked: "Discount write access is not requested or implemented." },
  content: { eyebrow: "Content intelligence", title: "Create content direction from verified context.", description: "Cresna creates reviewable product and positioning copy from approved catalog and Business Brain records. It does not publish to storefront or marketing channels.", action: "/app/ai-studio", actionLabel: "Open AI Action Studio" },
  markets: { eyebrow: "Markets", title: "Market expansion data is not connected yet.", description: "Cresna does not claim to analyze localized storefronts, duties, international pricing, or market settings without a supported Shopify Markets integration.", blocked: "Shopify Markets data is not synced in this workspace." },
  finance: { eyebrow: "Finance signals", title: "Separate reported revenue from unconnected profitability.", description: "Cresna shows connected net revenue, orders, and refund evidence. It does not calculate profit without verified costs, payouts, tax, fees, and expenses." },
  analytics: { eyebrow: "Analytics baseline", title: "Understand what Cresna can prove today.", description: "Review connected order, checkout, revenue, catalog, and Growth Score evidence. Missing sources remain visible instead of being estimated." },
};

const money = (value: number, currency: string) => new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 0 }).format(value);
const percent = (part: number, whole: number) => whole ? `${Math.round((part / whole) * 100)}%` : "Unavailable";

export default function CommerceModule({ section }: { section: CommerceSection }) {
  const [, setLocation] = useLocation();
  const spec = copy[section];
  const { data: analytics, isLoading: analyticsLoading } = trpc.analytics.overview.useQuery();
  const { data: intelligence, isLoading: intelligenceLoading } = trpc.intelligence.overview.useQuery();
  const { data: catalog, isLoading: catalogLoading } = trpc.catalog.products.useQuery();
  const { data: drafts, isLoading: draftsLoading } = trpc.aiActions.list.useQuery();
  const metrics = (analytics?.dailyMetrics ?? []) as Metric[];
  const products = (catalog ?? []) as Product[];
  const queuedDrafts = (drafts ?? []) as Draft[];
  const score = intelligence?.score as Score | undefined;
  const currency = analytics?.store?.currency || "USD";
  const loading = analyticsLoading || intelligenceLoading || catalogLoading || draftsLoading;
  const hasStore = Boolean(analytics?.store);
  const totals = metrics.reduce((all, metric) => ({ orders: all.orders + metric.orderCount, revenue: all.revenue + Number(metric.netRevenue), refunds: all.refunds + metric.refundCount, customers: all.customers + metric.customerCount, checkouts: all.checkouts + metric.checkoutCount, abandoned: all.abandoned + metric.abandonedCheckoutCount }), { orders: 0, revenue: 0, refunds: 0, customers: 0, checkouts: 0, abandoned: 0 });

  if (unavailable.has(section)) return <WorkspaceFrame eyebrow={spec.eyebrow} title={spec.title} description={spec.description}><EmptyWorkspaceCard title={spec.blocked || "This capability is not connected yet."} action="Back to overview" onAction={() => setLocation("/app")}>{spec.description}</EmptyWorkspaceCard></WorkspaceFrame>;
  if (loading) return <WorkspaceFrame eyebrow={spec.eyebrow} title={spec.title} description={spec.description}><div className="grid min-h-[300px] place-items-center"><Loader2 className="h-5 w-5 animate-spin text-primary" /></div></WorkspaceFrame>;
  if (!hasStore && !["drafts", "content", "growth"].includes(section)) return <WorkspaceFrame eyebrow={spec.eyebrow} title={spec.title} description={spec.description}><EmptyWorkspaceCard title="Connect Shopify to create a reliable baseline" action="Review connection" onAction={() => setLocation("/app/connect")}>Cresna does not invent commerce metrics. Approve a connection first, then it will display only the sources the store sync can verify.</EmptyWorkspaceCard></WorkspaceFrame>;

  return <WorkspaceFrame eyebrow={spec.eyebrow} title={spec.title} description={spec.description}><ModuleBody section={section} metrics={metrics} totals={totals} currency={currency} products={products} drafts={queuedDrafts} score={score} onNavigate={setLocation} action={spec.action} actionLabel={spec.actionLabel} /></WorkspaceFrame>;
}

function ModuleBody({ section, metrics, totals, currency, products, drafts, score, onNavigate, action, actionLabel }: { section: CommerceSection; metrics: Metric[]; totals: { orders: number; revenue: number; refunds: number; customers: number; checkouts: number; abandoned: number }; currency: string; products: Product[]; drafts: Draft[]; score: Score | undefined; onNavigate: (path: string) => void; action?: string; actionLabel?: string }) {
  const cta = action ? <Button onClick={() => onNavigate(action)} className="rounded-full text-xs font-bold">{actionLabel}</Button> : null;
  if (section === "products") return <div className="space-y-5"><CatalogView products={products} />{cta}</div>;
  if (section === "drafts") return <div className="space-y-5"><DraftView drafts={drafts} /><Notice title="Review is a permission boundary" detail="Cresna records an approve/reject decision but does not push the draft to Shopify. Publishing remains unavailable until explicit write permissions and a supported integration are configured." />{cta}</div>;
  if (section === "content") return <div className="space-y-5"><ContentView /><DraftView drafts={drafts} /><Notice title="Writing capability" detail="Cresna can read permitted context and create private product, SEO, and positioning drafts. It cannot publish, schedule, or contact customers without a future explicit write permission." />{cta}</div>;
  if (section === "growth") return <div className="space-y-5"><GrowthView coverage={score?.coveragePercent ?? 0} />{cta}</div>;
  if (section === "orders") return <SignalView cards={[[ReceiptText, "Reported orders", totals.orders.toLocaleString(), `${metrics.length} synced reporting days`], [Landmark, "Average order value", totals.orders ? money(totals.revenue / totals.orders, currency) : "Unavailable", "Net revenue ÷ reported orders"], [TrendingUp, "Checkout completion", percent(totals.orders, totals.checkouts), totals.checkouts ? `${totals.abandoned.toLocaleString()} reported abandoned checkouts` : "Checkout source unavailable"], [AlertCircle, "Refund signal", percent(totals.refunds, totals.orders), `${totals.refunds.toLocaleString()} refund events reported`]]} table="orders" metrics={metrics} currency={currency} notice="Compare verified trend movement before changing an offer. Cresna is designed for evidence and decisions—not fulfillment or individual-order management." />;
  if (section === "customers") return <SignalView cards={[[UsersRound, "Customer observations", totals.customers.toLocaleString(), "Aggregate count across reported days"], [ReceiptText, "Orders per observation", totals.customers ? (totals.orders / totals.customers).toFixed(2) : "Unavailable", "Directional only; not a retention rate"], [TrendingUp, "Latest customer count", metrics.at(-1)?.customerCount.toLocaleString() || "Unavailable", metrics.at(-1) ? new Date(metrics.at(-1)!.metricDate).toLocaleDateString() : "No reporting date"], [AlertCircle, "Individual data", "Protected", "No profiles, segments, or outreach"]]} table="customers" metrics={metrics} currency={currency} notice="Daily customer counts are aggregate reporting evidence—not a customer database, cohort retention result, or substitute for Shopify segmentation." />;
  if (section === "finance") return <SignalView cards={[[Landmark, "Reported net revenue", money(totals.revenue, currency), `${metrics.length} reported days`], [ReceiptText, "Revenue per report day", metrics.length ? money(totals.revenue / metrics.length, currency) : "Unavailable", "Average—not a forecast"], [AlertCircle, "Refund events", totals.refunds.toLocaleString(), `${percent(totals.refunds, totals.orders)} of reported orders`], [Landmark, "Profit calculation", "Unavailable", "Costs, fees, tax, payouts not connected"]]} table="finance" metrics={metrics} currency={currency} notice="Cresna will not turn net revenue and refund events into profit, cash-flow, payout, or tax claims without the verified inputs needed for that calculation." />;
  return <AnalyticsView metrics={metrics} products={products} score={score} totals={totals} currency={currency} />;
}

function SignalView({ cards, table, metrics, currency, notice }: { cards: Array<[ComponentType<{ className?: string }>, string, string, string]>; table: "orders" | "customers" | "finance"; metrics: Metric[]; currency: string; notice: string }) { return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([Icon, label, value, detail]) => <MetricCard key={label} icon={Icon} label={label} value={value} detail={detail} />)}</div><EvidenceTable variant={table} rows={metrics.slice(-14).reverse()} currency={currency} /><Notice title="Decision use" detail={notice} /></div>; }
function AnalyticsView({ metrics, products, score, totals, currency }: { metrics: Metric[]; products: Product[]; score: Score | undefined; totals: { orders: number; revenue: number; refunds: number; customers: number; checkouts: number; abandoned: number }; currency: string }) { return <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={BarChart3} label="Growth Score" value={score?.overallScore?.toString() || "—"} detail={score ? `${score.coveragePercent ?? 0}% evidence coverage` : "Requires connected evidence"} /><MetricCard icon={ReceiptText} label="Reported orders" value={totals.orders.toLocaleString()} detail={`${metrics.length} synced days`} /><MetricCard icon={Landmark} label="Reported revenue" value={money(totals.revenue, currency)} detail="No extrapolation" /><MetricCard icon={Package} label="Catalog records" value={products.length.toLocaleString()} detail="Verified synced product records" /></div><section className="rounded-[1.25rem] border border-border bg-card p-6 text-card-foreground"><p className="text-sm font-bold">Evidence coverage map</p><p className="mt-1 text-xs leading-5 text-muted-foreground">Cresna shows which foundations are connected before drawing an insight.</p><div className="mt-5 grid gap-3 sm:grid-cols-3"><Coverage label="Daily reporting" detail={metrics.length ? `${metrics.length} reported days` : "No reported days"} ready={metrics.length > 0} /><Coverage label="Catalog records" detail={products.length ? `${products.length} synced products` : "No synced products"} ready={products.length > 0} /><Coverage label="Profit & market inputs" detail="Costs, fees, and market settings not connected" ready={false} /></div></section><EvidenceTable variant="analytics" rows={metrics.slice(-14).reverse()} currency={currency} /></div>; }
function GrowthView({ coverage }: { coverage: number }) { return <section className="rounded-[1.35rem] border border-border bg-card p-6 text-card-foreground"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="eyebrow text-[10px] text-muted-foreground">Evidence-to-action loop</p><h2 className="mt-2 text-xl font-extrabold tracking-[-0.04em]">Choose a next step that can be measured.</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-muted-foreground">Cresna links available evidence to merchant-approved opportunities. No recommendation becomes a Shopify change without an explicit permission and a supported write path.</p></div><div className="rounded-xl bg-secondary px-4 py-3"><p className="text-[10px] font-bold uppercase tracking-[0.08em] text-muted-foreground">Current evidence</p><p className="mt-1 text-xl font-extrabold">{coverage}% coverage</p></div></div><div className="mt-6 grid gap-3 md:grid-cols-4">{[["1", "Connect", "Authorize only the read data Cresna needs."], ["2", "Prioritize", "Review evidence-backed opportunities."], ["3", "Draft", "Generate content for review."], ["4", "Measure", "Record outcome evidence."]].map(([number, title, detail]) => <div key={number} className="rounded-xl border border-border bg-background p-4"><p className="text-xs font-bold text-primary">{number}</p><p className="mt-3 text-sm font-bold">{title}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">{detail}</p></div>)}</div></section>; }
function MetricCard({ icon: Icon, label, value, detail }: { icon: ComponentType<{ className?: string }>; label: string; value: string; detail: string }) { return <section className="rounded-[1.25rem] border border-border bg-card p-5 text-card-foreground"><Icon className="h-4 w-4 text-primary" /><p className="mt-4 text-[10px] font-bold uppercase tracking-[0.08em] text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-extrabold tracking-[-0.05em]">{value}</p><p className="mt-2 text-[11px] text-muted-foreground">{detail}</p></section>; }
function Notice({ title, detail }: { title: string; detail: string }) { return <section className="rounded-[1.25rem] border border-border bg-card p-6 text-card-foreground"><p className="text-sm font-bold">{title}</p><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{detail}</p></section>; }
function EvidenceTable({ variant, rows, currency }: { variant: "orders" | "customers" | "finance" | "analytics"; rows: Metric[]; currency: string }) { const title = variant === "orders" ? "Order & checkout evidence" : variant === "customers" ? "Aggregate customer evidence" : variant === "finance" ? "Revenue & refund evidence" : "Daily operating baseline"; return <section className="overflow-hidden rounded-[1.25rem] border border-border bg-card text-card-foreground"><div className="border-b border-border px-6 py-5"><p className="text-sm font-bold">{title}</p><p className="mt-1 text-xs text-muted-foreground">Only connected-store reporting days are listed. Blank dates are not estimated.</p></div>{rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b border-border text-[10px] uppercase tracking-[0.08em] text-muted-foreground"><tr><th className="px-6 py-3">Date</th>{variant !== "finance" && <th className="px-4 py-3">Orders</th>}{(variant === "orders" || variant === "analytics") && <th className="px-4 py-3">Checkouts</th>}{(variant === "customers" || variant === "analytics") && <th className="px-4 py-3">Customers</th>}<th className="px-4 py-3">Refunds</th><th className="px-6 py-3 text-right">Net revenue</th></tr></thead><tbody>{rows.map(row => <tr key={row.id} className="border-b border-border/70 last:border-0"><td className="px-6 py-3 font-semibold">{new Date(row.metricDate).toLocaleDateString()}</td>{variant !== "finance" && <td className="px-4 py-3 text-muted-foreground">{row.orderCount.toLocaleString()}</td>}{(variant === "orders" || variant === "analytics") && <td className="px-4 py-3 text-muted-foreground">{row.checkoutCount.toLocaleString()}</td>}{(variant === "customers" || variant === "analytics") && <td className="px-4 py-3 text-muted-foreground">{row.customerCount.toLocaleString()}</td>}<td className="px-4 py-3 text-muted-foreground">{row.refundCount.toLocaleString()}</td><td className="px-6 py-3 text-right font-semibold">{money(Number(row.netRevenue), currency)}</td></tr>)}</tbody></table></div> : <p className="px-6 py-8 text-sm text-muted-foreground">The store is connected, but no reported daily evidence is available yet.</p>}</section>; }
function CatalogView({ products }: { products: Product[] }) { const description = products.filter(p => (p.descriptionHtml || "").replace(/<[^>]*>/g, " ").trim().length >= 80).length; const seo = products.filter(p => p.seoTitle && p.seoDescription).length; const media = products.filter(p => (p.mediaCount || 0) > 0).length; return <section className="rounded-[1.25rem] border border-border bg-card p-6 text-card-foreground"><div className="flex items-center gap-2"><Package className="h-4 w-4 text-primary" /><p className="text-sm font-bold">Connected catalog · {products.length} products</p></div>{products.length ? <><div className="mt-5 grid gap-3 sm:grid-cols-3"><Coverage label="Descriptions with detail" detail={`${description} / ${products.length}`} ready={description === products.length} /><Coverage label="SEO title + description" detail={`${seo} / ${products.length}`} ready={seo === products.length} /><Coverage label="Products with media" detail={`${media} / ${products.length}`} ready={media === products.length} /></div><div className="mt-5 divide-y divide-border">{products.slice(0, 12).map(p => <div key={p.id} className="flex items-center justify-between gap-4 py-3"><p className="text-sm font-semibold">{p.title}</p><span className="text-[11px] text-muted-foreground">{p.seoTitle && p.seoDescription ? "SEO present" : "SEO incomplete"}</span></div>)}</div></> : <p className="mt-4 text-sm text-muted-foreground">No catalog records are available yet. Cresna will wait for a completed Shopify sync.</p>}</section>; }
function DraftView({ drafts }: { drafts: Draft[] }) { return <section className="rounded-[1.25rem] border border-border bg-card p-6 text-card-foreground"><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-primary" /><p className="text-sm font-bold">Review queue · {drafts.length} drafts</p></div>{drafts.length ? <div className="mt-5 divide-y divide-border">{drafts.slice(0, 12).map(({ draft, product }) => <div key={draft.id} className="flex items-center justify-between gap-4 py-3"><p className="text-sm font-semibold">{draft.actionType === "positioning" ? "Brand positioning" : product?.title || "Catalog item"}</p><span className="rounded-full bg-secondary px-2.5 py-1 text-[10px] font-bold text-secondary-foreground">{draft.status}</span></div>)}</div> : <p className="mt-4 text-sm text-muted-foreground">No AI drafts are stored yet. Cresna creates drafts only from verified catalog fields and your approved context.</p>}</section>; }
function ContentView() { return <section className="rounded-[1.25rem] border border-border bg-card p-6 text-card-foreground"><div className="flex items-center gap-2"><FilePenLine className="h-4 w-4 text-primary" /><p className="text-sm font-bold">Writing grounded in approved context</p></div><div className="mt-5 grid gap-3 md:grid-cols-3">{[["Product descriptions", "Uses connected catalog fields and names missing facts instead of inventing them."], ["SEO basics", "Creates reviewable titles and descriptions from the same verified fields."], ["Brand positioning", "Uses approved Business Brain context—not fabricated market research."]].map(([title, detail]) => <div key={title} className="rounded-xl border border-border bg-secondary/50 p-4"><p className="text-sm font-bold">{title}</p><p className="mt-2 text-xs leading-5 text-muted-foreground">{detail}</p></div>)}</div></section>; }
function Coverage({ label, detail, ready }: { label: string; detail: string; ready: boolean }) { return <div className="rounded-xl bg-secondary p-4"><p className="text-[10px] font-bold uppercase tracking-[0.08em] text-muted-foreground">{label}</p><p className={`mt-3 text-sm font-bold ${ready ? "text-foreground" : "text-muted-foreground"}`}>{ready ? "Complete" : "Needs evidence"}</p><p className="mt-1 text-[11px] leading-5 text-muted-foreground">{detail}</p></div>; }
