import { EmptyWorkspaceCard, WorkspaceFrame } from "@/components/WorkspaceFrame";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { BarChart3, FileText, Landmark, Loader2, Package, ShoppingCart, UsersRound } from "lucide-react";
import { useLocation } from "wouter";

export type CommerceSection = "orders" | "drafts" | "shipping" | "products" | "customers" | "growth" | "discounts" | "content" | "markets" | "finance" | "analytics";

const unavailable = new Set<CommerceSection>(["shipping", "discounts", "markets"]);
const copy: Record<CommerceSection, { eyebrow: string; title: string; description: string; blocked?: string; action?: string; actionLabel?: string }> = {
  orders: { eyebrow: "Commerce intelligence", title: "Order signals without fabricated order records.", description: "Cresna currently turns approved Shopify order syncs into aggregated daily order, revenue, checkout, and refund evidence. Individual order management is not yet an in-app Cresna feature." },
  drafts: { eyebrow: "Draft review", title: "Every AI draft stays reviewable.", description: "Drafts are created only from your approved Business Brain and verified catalog records. Nothing publishes to Shopify automatically.", action: "/app/ai-studio", actionLabel: "Open AI Action Studio" },
  shipping: { eyebrow: "Shipping labels", title: "Shipping labels are not connected yet.", description: "Cresna does not currently create, buy, or manage shipping labels. That requires a dedicated fulfillment integration and explicit write permissions.", blocked: "No shipping-label integration or fulfillment write scope is configured." },
  products: { eyebrow: "Catalog intelligence", title: "See the products Cresna can verify.", description: "This list is sourced from your connected Shopify catalog. Product-writing assistance remains a reviewable draft until a future merchant-approved write integration exists.", action: "/app/ai-studio", actionLabel: "Create a reviewable draft" },
  customers: { eyebrow: "Customer signals", title: "Customer trends, not a customer database.", description: "Cresna can use approved aggregate customer counts from daily reporting. It does not expose individual customer profiles, segments, or marketing outreach without a specific supported workflow." },
  growth: { eyebrow: "Growth operating system", title: "Turn evidence into a measured next move.", description: "Growth combines your saved context, connected-store evidence, ranked opportunities, reviewable drafts, and outcome tracking.", action: "/app/actions", actionLabel: "Review opportunities" },
  discounts: { eyebrow: "Discounts", title: "Discount creation is not connected yet.", description: "Cresna can surface pricing and offer-readiness evidence, but it does not create Shopify discounts without discount write scopes and an explicit merchant approval flow.", blocked: "Discount write access is not requested or implemented." },
  content: { eyebrow: "Content intelligence", title: "Create content direction from verified product context.", description: "Use Cresna’s AI Action Studio for merchant-reviewed product and positioning drafts. Publishing to storefront, social, or marketing channels is not connected.", action: "/app/ai-studio", actionLabel: "Open content drafts" },
  markets: { eyebrow: "Markets", title: "Market expansion data is not connected yet.", description: "Cresna does not currently claim to analyze localized storefronts, duties, international pricing, or market settings without a supported Shopify Markets data integration.", blocked: "Shopify Markets data is not synced in this workspace." },
  finance: { eyebrow: "Finance signals", title: "Revenue and refund evidence—without invented profit.", description: "Cresna can show connected net-revenue, order, and refund reporting. It does not present a profit-and-loss statement without verified cost, payout, tax, and expense data." },
  analytics: { eyebrow: "Analytics", title: "A practical store-performance baseline.", description: "Review available revenue, order, checkout, product, and growth-score evidence. Cresna labels missing sources instead of generating performance claims.", action: "/app", actionLabel: "Open analytics overview" },
};

const money = (value: number, currency: string) => new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 0 }).format(value);

export default function CommerceModule({ section }: { section: CommerceSection }) {
  const [, setLocation] = useLocation();
  const spec = copy[section];
  const { data: analytics, isLoading: analyticsLoading } = trpc.analytics.overview.useQuery();
  const { data: catalog, isLoading: catalogLoading } = trpc.catalog.products.useQuery();
  const { data: drafts, isLoading: draftsLoading } = trpc.aiActions.list.useQuery();
  const metrics = analytics?.dailyMetrics ?? [];
  const currency = analytics?.store?.currency || "USD";
  const orders = metrics.reduce((total, metric) => total + metric.orderCount, 0);
  const revenue = metrics.reduce((total, metric) => total + Number(metric.netRevenue), 0);
  const refunds = metrics.reduce((total, metric) => total + metric.refundCount, 0);
  const customers = metrics.reduce((total, metric) => total + metric.customerCount, 0);
  const loading = analyticsLoading || catalogLoading || draftsLoading;

  const body = unavailable.has(section)
    ? <EmptyWorkspaceCard title={spec.blocked || "This capability is not connected yet."} action="Back to overview" onAction={() => setLocation("/app")}>{spec.description}</EmptyWorkspaceCard>
    : loading
      ? <div className="grid min-h-[300px] place-items-center"><Loader2 className="h-5 w-5 animate-spin text-primary" /></div>
      : !analytics?.store && section !== "drafts" && section !== "content" && section !== "growth"
        ? <EmptyWorkspaceCard title="Connect Shopify to create a reliable baseline" action="Review connection" onAction={() => setLocation("/app/connect")}>Cresna does not invent commerce metrics. Approve a connection first, then it will display only the sources the store sync can verify.</EmptyWorkspaceCard>
        : <div className="space-y-5"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat icon={ShoppingCart} label="Orders" value={orders.toLocaleString()} detail={`${metrics.length} reporting days`} /><Stat icon={Landmark} label="Net revenue" value={money(revenue, currency)} detail="Available reporting days" /><Stat icon={UsersRound} label="Customer count" value={customers.toLocaleString()} detail="Aggregate daily reporting" /><Stat icon={BarChart3} label="Refund events" value={refunds.toLocaleString()} detail="No profit claim without costs" /></div>{section === "orders" || section === "customers" || section === "finance" || section === "analytics" ? <DailyEvidence rows={metrics.slice(-14).reverse()} currency={currency} /> : null}{section === "products" ? <CatalogList products={catalog ?? []} /> : null}{section === "drafts" || section === "content" ? <DraftList drafts={drafts ?? []} /> : null}{section === "customers" ? <EvidenceNotice title="What is available today" detail="Aggregate customer counts contribute to connected-store reporting. Individual customers, support history, segments, and outreach are intentionally not exposed in Cresna today." /> : null}{section === "orders" ? <EvidenceNotice title="What is available today" detail="Cresna displays aggregate order trends, not individual fulfillment or order-management records. Use Shopify Admin for order operations while Cresna focuses on evidence and decisions." /> : null}{section === "finance" ? <EvidenceNotice title="Financial boundary" detail="Net revenue and refund events are available from the current sync. Costs, payouts, fees, taxes, and operating expenses are not fully connected, so Cresna will not calculate profit or cash flow." /> : null}{section === "growth" ? <EvidenceNotice title="The growth loop" detail="Save brand context, review evidence-backed opportunities, generate a reviewable draft, approve the direction, and measure the recorded outcome." /> : null}{section === "analytics" ? <EvidenceNotice title="Analytics boundary" detail="Metrics reflect approved store sync data and can be incomplete while the connection is new. Cresna does not infer missing checkout, competitor, external-market, or AI-search data." /> : null}{spec.action ? <Button onClick={() => setLocation(spec.action!)} className="rounded-full text-xs font-bold">{spec.actionLabel}</Button> : null}</div>;

  return <WorkspaceFrame eyebrow={spec.eyebrow} title={spec.title} description={spec.description}>{body}</WorkspaceFrame>;
}

function Stat({ icon: Icon, label, value, detail }: { icon: typeof ShoppingCart; label: string; value: string; detail: string }) { return <section className="rounded-[1.25rem] border border-border bg-card p-5 text-card-foreground"><Icon className="h-4 w-4 text-primary" /><p className="mt-4 text-[10px] font-bold uppercase tracking-[0.08em] text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-extrabold tracking-[-0.05em]">{value}</p><p className="mt-2 text-[11px] text-muted-foreground">{detail}</p></section>; }
function EvidenceNotice({ title, detail }: { title: string; detail: string }) { return <section className="rounded-[1.25rem] border border-border bg-card p-6 text-card-foreground"><p className="text-sm font-bold">{title}</p><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{detail}</p></section>; }
function DailyEvidence({ rows, currency }: { rows: Array<{ id: number; metricDate: Date; orderCount: number; customerCount: number; refundCount: number; netRevenue: string | number }>; currency: string }) { return <section className="overflow-hidden rounded-[1.25rem] border border-border bg-card text-card-foreground"><div className="border-b border-border px-6 py-5"><p className="text-sm font-bold">Daily evidence</p><p className="mt-1 text-xs text-muted-foreground">Only reported connected-store days are listed. Empty reporting dates are not estimated.</p></div>{rows.length ? <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="border-b border-border text-[10px] uppercase tracking-[0.08em] text-muted-foreground"><tr><th className="px-6 py-3">Date</th><th className="px-4 py-3">Orders</th><th className="px-4 py-3">Customers</th><th className="px-4 py-3">Refund events</th><th className="px-6 py-3 text-right">Net revenue</th></tr></thead><tbody>{rows.map(row => <tr key={row.id} className="border-b border-border/70 last:border-0"><td className="px-6 py-3 font-semibold">{new Date(row.metricDate).toLocaleDateString()}</td><td className="px-4 py-3 text-muted-foreground">{row.orderCount.toLocaleString()}</td><td className="px-4 py-3 text-muted-foreground">{row.customerCount.toLocaleString()}</td><td className="px-4 py-3 text-muted-foreground">{row.refundCount.toLocaleString()}</td><td className="px-6 py-3 text-right font-semibold">{money(Number(row.netRevenue), currency)}</td></tr>)}</tbody></table></div> : <p className="px-6 py-8 text-sm text-muted-foreground">The store is connected, but no reported daily evidence is available yet.</p>}</section>; }
function CatalogList({ products }: { products: Array<{ id: number; title: string; descriptionHtml: string | null; seoTitle: string | null; seoDescription: string | null; mediaCount: number | null }> }) { const descriptionCoverage = products.filter(product => (product.descriptionHtml || "").replace(/<[^>]*>/g, " ").trim().length >= 80).length; const seoCoverage = products.filter(product => product.seoTitle && product.seoDescription).length; const mediaCoverage = products.filter(product => (product.mediaCount || 0) > 0).length; return <section className="rounded-[1.25rem] border border-border bg-card p-6 text-card-foreground"><div className="flex items-center gap-2"><Package className="h-4 w-4 text-primary" /><p className="text-sm font-bold">Connected catalog · {products.length} products</p></div>{products.length ? <><div className="mt-5 grid gap-3 sm:grid-cols-3"><Coverage label="Descriptions with detail" value={descriptionCoverage} total={products.length} /><Coverage label="SEO title + description" value={seoCoverage} total={products.length} /><Coverage label="Products with media" value={mediaCoverage} total={products.length} /></div><div className="mt-5 divide-y divide-border">{products.slice(0, 12).map(product => <div key={product.id} className="flex items-center justify-between gap-4 py-3"><p className="text-sm font-semibold">{product.title}</p><span className="text-[11px] text-muted-foreground">{product.seoTitle && product.seoDescription ? "SEO present" : "SEO incomplete"}</span></div>)}</div></> : <p className="mt-4 text-sm text-muted-foreground">No catalog records are available yet. Cresna will wait for a completed Shopify sync.</p>}</section>; }
function Coverage({ label, value, total }: { label: string; value: number; total: number }) { return <div className="rounded-xl bg-secondary p-4"><p className="text-[10px] font-bold uppercase tracking-[0.08em] text-muted-foreground">{label}</p><p className="mt-2 text-xl font-extrabold tracking-[-0.04em]">{value} <span className="text-sm text-muted-foreground">/ {total}</span></p></div>; }
function DraftList({ drafts }: { drafts: Array<{ draft: { id: number; actionType: string; status: string }; product: { title: string } | null }> }) { return <section className="rounded-[1.25rem] border border-border bg-card p-6 text-card-foreground"><div className="flex items-center gap-2"><FileText className="h-4 w-4 text-primary" /><p className="text-sm font-bold">Review queue · {drafts.length} drafts</p></div>{drafts.length ? <div className="mt-5 divide-y divide-border">{drafts.slice(0, 12).map(({ draft, product }) => <div key={draft.id} className="flex items-center justify-between gap-4 py-3"><p className="text-sm font-semibold">{draft.actionType === "positioning" ? "Brand positioning" : product?.title || "Catalog item"}</p><span className="rounded-full bg-secondary px-2.5 py-1 text-[10px] font-bold text-secondary-foreground">{draft.status}</span></div>)}</div> : <p className="mt-4 text-sm text-muted-foreground">No AI drafts are stored yet. Cresna only creates drafts from verified catalog fields and your approved context.</p>}</section>; }
