import { EmptyWorkspaceCard, WorkspaceFrame } from "@/components/WorkspaceFrame";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { ArrowUpRight, Loader2 } from "lucide-react";
import { useLocation } from "wouter";

const money = (value: string | number, currency = "USD") => new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 0 }).format(Number(value));

export default function Dashboard() {
  const [, setLocation] = useLocation();
  const { data, isLoading } = trpc.analytics.overview.useQuery();
  const { data: intelligence } = trpc.intelligence.overview.useQuery();
  const metrics = data?.dailyMetrics ?? [];
  const store = data?.store;
  const currency = store?.currency || "USD";
  const totalRevenue = metrics.reduce((sum, metric) => sum + Number(metric.netRevenue), 0);
  const totalOrders = metrics.reduce((sum, metric) => sum + metric.orderCount, 0);
  const totalCheckouts = metrics.reduce((sum, metric) => sum + metric.checkoutCount, 0);
  const totalAbandoned = metrics.reduce((sum, metric) => sum + metric.abandonedCheckoutCount, 0);
  const latestProducts = data?.productMetrics.filter((metric, index, all) => all.findIndex(item => item.shopifyProductId === metric.shopifyProductId) === index).slice(0, 5) ?? [];
  const highestMetric = Math.max(...metrics.map(metric => Number(metric.netRevenue)), 1);

  return <WorkspaceFrame eyebrow="Store health" title={store ? `${store.displayName} at a glance.` : "A calm view of what matters next."} description={store ? "Live metrics are calculated from your connected store’s approved data. Product and funnel views are only shown where source data is available." : "Build your Growth Profile, then connect a Shopify store. Cresna will ground sales, product, and checkout insights in your approved store data."}>
    {isLoading ? <div className="grid min-h-[300px] place-items-center"><Loader2 className="h-5 w-5 animate-spin text-[#7c9b1e]" /></div> : !store ? <EmptyWorkspaceCard title="Start with your Growth Profile" action="Set growth goals" onAction={() => setLocation("/app/profile")}>Cresna does not invent performance numbers. Set your priorities, then connect Shopify so we can build a reliable baseline.</EmptyWorkspaceCard> : metrics.length === 0 ? <EmptyWorkspaceCard title="Your store is connected. We’re waiting for its first metrics." action="Manage connection" onAction={() => setLocation("/app/connect")}>A dashboard will appear after the initial Shopify data synchronization finishes. Until then, Cresna will not estimate sales performance.</EmptyWorkspaceCard> : <div className="space-y-5">
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><MetricCard label="Net revenue" value={money(totalRevenue, currency)} detail={`${metrics.length} reported days`} /><MetricCard label="Orders" value={totalOrders.toLocaleString()} detail="Across available reporting days" /><MetricCard label="Checkout completion" value={totalCheckouts ? `${Math.round((totalOrders / totalCheckouts) * 100)}%` : "Unavailable"} detail={totalCheckouts ? `${totalAbandoned.toLocaleString()} abandoned checkouts` : "No checkout data reported"} /><MetricCard label={intelligence?.score?.status === "needs_more_data" ? "Growth Score" : "Current Growth Score"} value={intelligence?.score?.overallScore?.toString() || "—"} detail={intelligence?.score ? `${intelligence.score.coveragePercent}% evidence coverage · see Business Brain` : "Connect and scan to calculate only available components"} /></div>
      <div className="grid gap-5 lg:grid-cols-[1.45fr_0.9fr]"><Card className="border-[#17201e]/12 bg-[#fdfdfb] shadow-none"><CardContent className="p-6"><div className="flex items-start justify-between"><div><p className="eyebrow text-[10px] text-[#65706b]">Revenue trend</p><p className="mt-2 text-sm text-[#65706b]">Net revenue by reported day</p></div><span className="text-[11px] font-bold text-[#65706b]">{metrics.length} days</span></div><div className="mt-8 flex h-44 items-end gap-1.5">{metrics.map(metric => <div key={metric.metricDate.toString()} className="group relative flex-1 rounded-t-sm bg-[#d9fa55]" style={{ height: `${Math.max((Number(metric.netRevenue) / highestMetric) * 100, 3)}%` }} title={`${new Date(metric.metricDate).toLocaleDateString()}: ${money(metric.netRevenue, currency)}`} />)}</div><div className="mt-3 flex justify-between text-[10px] text-[#7a847e]"><span>{new Date(metrics[0]!.metricDate).toLocaleDateString()}</span><span>{new Date(metrics[metrics.length - 1]!.metricDate).toLocaleDateString()}</span></div></CardContent></Card>
        <Card className="border-[#17201e]/12 bg-[#17201e] text-[#f8f7f2] shadow-none"><CardContent className="p-6"><p className="eyebrow text-[10px] text-[#b6c1bb]">Conversion funnel</p><p className="mt-2 text-sm text-[#b6c1bb]">Available checkout activity</p><div className="mt-8 space-y-4">{[["Checkouts", totalCheckouts], ["Orders", totalOrders], ["Abandoned", totalAbandoned]].map(([label, value]) => <div key={String(label)}><div className="flex justify-between text-xs"><span>{label}</span><span className="font-bold">{Number(value).toLocaleString()}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-[#d9fa55]" style={{ width: `${totalCheckouts ? Math.max((Number(value) / totalCheckouts) * 100, 2) : 0}%` }} /></div></div>)}</div></CardContent></Card></div>
      <Card className="border-[#17201e]/12 bg-[#fdfdfb] shadow-none"><CardContent className="p-6"><div className="flex items-center justify-between"><div><p className="eyebrow text-[10px] text-[#65706b]">Product performance</p><p className="mt-2 text-sm text-[#65706b]">Most recently synchronized product metrics</p></div><Button variant="link" onClick={() => setLocation("/app/actions")} className="h-auto gap-1 px-0 text-[11px] font-bold text-foreground">View action feed <ArrowUpRight className="h-3.5 w-3.5" /></Button></div><div className="mt-6 overflow-x-auto"><table className="w-full min-w-[560px] text-left"><thead className="border-b border-[#17201e]/10 text-[10px] uppercase tracking-[0.09em] text-[#65706b]"><tr><th className="pb-3 font-medium">Product</th><th className="pb-3 font-medium">Orders</th><th className="pb-3 font-medium">Net revenue</th><th className="pb-3 font-medium">Refunds</th></tr></thead><tbody className="text-sm">{latestProducts.map(product => <tr key={product.id} className="border-b border-[#17201e]/7 last:border-0"><td className="py-4 font-semibold text-[#17201e]">{product.title}</td><td className="py-4 text-[#53605a]">{product.orderCount.toLocaleString()}</td><td className="py-4 font-semibold text-[#17201e]">{money(Number(product.grossRevenue) - Number(product.refundAmount), currency)}</td><td className="py-4 text-[#53605a]">{product.refundCount.toLocaleString()}</td></tr>)}</tbody></table></div></CardContent></Card>
    </div>}
  </WorkspaceFrame>;
}

function MetricCard({ label, value, detail }: { label: string; value: string; detail: string }) { return <Card className="border-[#17201e]/12 bg-[#fdfdfb] shadow-none"><CardContent className="p-5"><p className="eyebrow text-[10px] text-[#65706b]">{label}</p><p className="mt-4 text-3xl font-extrabold tracking-[-0.06em]">{value}</p><p className="mt-2 text-[11px] text-[#65706b]">{detail}</p></CardContent></Card>; }
