import { EmptyWorkspaceCard, UnpaidWorkspaceState, WorkspaceFrame } from "@/components/WorkspaceFrame";
import { useUnpaidPreview } from "@/contexts/UnpaidPreviewContext";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Check, ChevronRight, Loader2, RefreshCw, ShieldCheck, Sparkles } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";
import { toast } from "sonner";

const goalOptions = [["more_sales", "More sales"], ["more_customers", "More customers"], ["brand_awareness", "Brand awareness"], ["better_seo", "Better SEO"], ["competitor_edge", "Stand out from competitors"], ["improve_store", "Improve my store"], ["not_sure", "I’m not sure yet"]] as const;
type Goal = (typeof goalOptions)[number][0];
type ScoreComponent = { key: string; label: string; score: number | null; available: boolean; explanation: string };

function parseJson<T>(value: string | null | undefined, fallback: T): T { try { return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } }
function readGoals(value?: string) { return parseJson<unknown[]>(value, []).filter((goal): goal is Goal => typeof goal === "string" && goalOptions.some(([key]) => key === goal)); }

export default function GrowthProfile() {
  const { isUnpaidPreview, isCheckingPreview } = useUnpaidPreview();
  const [, setLocation] = useLocation();
  const { data: profile, isLoading } = trpc.growthProfile.me.useQuery();
  const { data: intelligence } = trpc.intelligence.overview.useQuery();
  const { data: opportunities } = trpc.recommendations.list.useQuery();
  const utils = trpc.useUtils();
  const [goals, setGoals] = useState<Goal[]>([]);
  const [brandSummary, setBrandSummary] = useState("");
  const [targetCustomer, setTargetCustomer] = useState("");
  const [brandVoice, setBrandVoice] = useState("");
  const [positioning, setPositioning] = useState("");
  const [differentiators, setDifferentiators] = useState("");
  const [brandValues, setBrandValues] = useState("");
  useEffect(() => { if (!profile) return; setGoals(readGoals(profile.goalsJson)); setBrandSummary(profile.brandSummary || ""); setTargetCustomer(profile.targetCustomer || ""); setBrandVoice(profile.brandVoice || ""); setPositioning(profile.positioning || ""); setDifferentiators(profile.differentiators || ""); setBrandValues(profile.brandValues || ""); }, [profile]);
  const components = useMemo(() => parseJson<ScoreComponent[]>(intelligence?.score?.componentsJson, []), [intelligence?.score?.componentsJson]);
  const sourceCoverage = useMemo(() => parseJson<Record<string, string>>(intelligence?.scan?.sourceCoverageJson, {}), [intelligence?.scan?.sourceCoverageJson]);
  const save = trpc.growthProfile.update.useMutation({ onSuccess: () => { utils.growthProfile.me.invalidate(); utils.intelligence.overview.invalidate(); toast.success("Business Brain saved"); }, onError: error => toast.error(error.message) });
  const refresh = trpc.intelligence.refresh.useMutation({ onSuccess: () => { utils.intelligence.overview.invalidate(); toast.success("Cresna refreshed the current scan evidence"); }, onError: error => toast.error(error.message) });
  const toggleGoal = (goal: Goal) => setGoals(current => current.includes(goal) ? current.filter(item => item !== goal) : [...current, goal]);
  const scoreLabel = intelligence?.score?.status === "ready" ? "Current Growth Score" : intelligence?.score?.status === "partial" ? "Partial Growth Score" : "Growth Score needs more data";

  if (isUnpaidPreview || isCheckingPreview) return <WorkspaceFrame eyebrow="Business Brain" title="Teach Cresna what growth means for your brand." description="Cresna remembers the context you approve, combines it with real connected-store evidence, and shows exactly where the score and opportunities come from."><UnpaidWorkspaceState title="Your Business Brain unlocks with a trial" detail="This real Growth Profile route is running without paid, trial, or beta access, so brand context, score evidence, and opportunities are intentionally not shown." /></WorkspaceFrame>;

  return <WorkspaceFrame eyebrow="Business Brain" title="Teach Cresna what growth means for your brand." description="Cresna remembers the context you approve, combines it with real connected-store evidence, and shows exactly where the score and opportunities come from.">
    {isLoading ? <div className="grid min-h-[300px] place-items-center"><Loader2 className="h-5 w-5 animate-spin text-[#7c9b1e]" /></div> : <div className="grid gap-5 xl:grid-cols-[1.12fr_0.88fr]">
      <section className="rounded-[1.35rem] border border-border bg-card p-6 text-card-foreground shadow-[0_8px_30px_rgba(23,32,30,0.04)] sm:p-8"><div><p className="eyebrow text-[10px] text-muted-foreground">Your persistent context</p><h2 className="mt-3 text-2xl font-extrabold tracking-[-0.05em]">The details that make AI work feel like yours.</h2><p className="mt-3 max-w-xl text-sm leading-6 text-muted-foreground">Cresna uses only the context you save here and the facts in your connected catalog. Missing details are treated as missing—not guessed.</p></div>
        <fieldset className="mt-7 grid gap-3 sm:grid-cols-2"><legend className="sr-only">Growth priorities</legend>{goalOptions.map(([key, label]) => <label key={key} className={`flex cursor-pointer items-center gap-3 rounded-xl border p-4 text-sm font-semibold transition-colors ${goals.includes(key) ? "border-primary bg-primary text-primary-foreground" : "border-border bg-background text-foreground hover:bg-secondary"}`}><input className="sr-only" type="checkbox" checked={goals.includes(key)} onChange={() => toggleGoal(key)} /><span className={`grid h-5 w-5 shrink-0 place-items-center rounded-full border ${goals.includes(key) ? "border-primary-foreground bg-primary-foreground text-primary" : "border-current/25"}`}>{goals.includes(key) ? <Check className="h-3.5 w-3.5" /> : null}</span>{label}</label>)}</fieldset>
        <div className="mt-8 grid gap-5"><label className="grid gap-2 text-xs font-bold text-foreground">What does your brand sell?<Textarea value={brandSummary} onChange={event => setBrandSummary(event.target.value)} placeholder="Everyday essentials designed for thoughtful home cooks." className="min-h-20 border-border bg-background text-sm" /></label><div className="grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-xs font-bold text-foreground">Who is it for?<Textarea value={targetCustomer} onChange={event => setTargetCustomer(event.target.value)} placeholder="The buyer you want to win." className="min-h-20 border-border bg-background text-sm" /></label><label className="grid gap-2 text-xs font-bold text-foreground">Brand voice<Input value={brandVoice} onChange={event => setBrandVoice(event.target.value)} placeholder="Warm, direct, quietly confident" className="border-border bg-background" /></label></div><label className="grid gap-2 text-xs font-bold text-foreground">Positioning<Textarea value={positioning} onChange={event => setPositioning(event.target.value)} placeholder="The clearest reason a buyer should choose you." className="min-h-20 border-border bg-background text-sm" /></label><div className="grid gap-5 sm:grid-cols-2"><label className="grid gap-2 text-xs font-bold text-foreground">What makes you different?<Textarea value={differentiators} onChange={event => setDifferentiators(event.target.value)} placeholder="Specific differentiators, not generic claims." className="min-h-20 border-border bg-background text-sm" /></label><label className="grid gap-2 text-xs font-bold text-foreground">Brand values<Textarea value={brandValues} onChange={event => setBrandValues(event.target.value)} placeholder="Values every generated draft should respect." className="min-h-20 border-border bg-background text-sm" /></label></div></div>
        <Button onClick={() => save.mutate({ goals, brandSummary, targetCustomer, brandVoice, positioning, differentiators, brandValues })} disabled={save.isPending || !goals.length} className="mt-8 h-11 rounded-full px-6 text-xs font-bold">{save.isPending ? "Saving…" : "Save Business Brain"}<ChevronRight className="ml-1 h-4 w-4" /></Button>
      </section>
      <aside className="space-y-5"><section className="rounded-[1.35rem] border border-[#17201e] bg-[#17201e] p-7 text-[#f8f7f2]"><div className="flex items-start justify-between gap-3"><div><p className="eyebrow text-[10px] text-[#b6c1bb]">Transparent score · v1</p><h2 className="mt-3 text-2xl font-extrabold tracking-[-0.05em]">{scoreLabel}</h2></div><span className="grid h-14 min-w-14 place-items-center rounded-2xl bg-[#d9fa55] px-2 text-2xl font-extrabold text-[#17201e]">{intelligence?.score?.overallScore ?? "—"}</span></div><p className="mt-4 text-sm leading-6 text-[#d9e1dc]">{intelligence?.score ? `${intelligence.score.coveragePercent}% of Cresna’s score components currently have enough verified data.` : "Connect and scan a store to calculate only the components Cresna can support."}</p><div className="mt-6 space-y-3 border-t border-white/15 pt-5">{components.length ? components.map(component => <div key={component.key} className="rounded-xl bg-white/[0.06] p-3"><div className="flex items-center justify-between gap-3"><p className="text-xs font-bold">{component.label}</p><span className="text-xs font-extrabold text-[#d9fa55]">{component.score ?? "—"}</span></div><p className="mt-2 text-[11px] leading-5 text-[#c7d0cb]">{component.explanation}</p></div>) : <p className="text-sm leading-6 text-[#d9e1dc]">No score has been calculated yet.</p>}</div>{intelligence?.store ? <Button onClick={() => refresh.mutate()} disabled={refresh.isPending} variant="outline" className="mt-6 h-10 w-full rounded-full border-white/25 bg-transparent text-xs font-bold text-[#f8f7f2] hover:bg-white/10 hover:text-[#f8f7f2]">{refresh.isPending ? <Loader2 className="mr-2 h-3.5 w-3.5 animate-spin" /> : <RefreshCw className="mr-2 h-3.5 w-3.5" />}Refresh current evidence</Button> : <Button onClick={() => setLocation("/app/connect")} className="mt-6 h-10 rounded-full bg-[#d9fa55] text-xs font-bold text-[#17201e] hover:bg-[#e4ff83]">Connect Shopify</Button>}</section>
        <section className="rounded-[1.35rem] border border-[#17201e]/12 bg-[#fdfdfb] p-6"><p className="eyebrow text-[10px] text-[#65706b]">What Cresna scanned</p><p className="mt-3 text-sm leading-6 text-[#53605a]">{intelligence?.scan?.summary || "No real scan has been completed. Cresna will not claim to see external competitors, reviews, social profiles, or AI-search results without a verifiable source."}</p><div className="mt-5 grid grid-cols-2 gap-2">{Object.entries(sourceCoverage).map(([source, status]) => <div key={source} className="rounded-lg bg-[#f5f5f1] px-3 py-2"><p className="text-[10px] font-bold capitalize text-[#17201e]">{source.replace(/([A-Z])/g, " $1")}</p><p className={`mt-1 text-[10px] font-bold ${status === "available" ? "text-[#63800b]" : "text-[#7b847f]"}`}>{status.replace(/_/g, " ")}</p></div>)}</div></section>
        <section className="rounded-[1.35rem] border border-[#17201e]/12 bg-[#fdfdfb] p-6"><p className="eyebrow text-[10px] text-[#65706b]">Opportunity Engine</p>{opportunities?.length ? <div className="mt-4 space-y-3">{opportunities.slice(0, 2).map(opportunity => <div key={opportunity.id} className="rounded-xl border border-[#17201e]/10 bg-[#f5f5f1] p-3"><p className="text-sm font-bold">{opportunity.title}</p><p className="mt-1 text-xs leading-5 text-[#65706b]">{opportunity.evidence}</p></div>)}<button type="button" onClick={() => setLocation("/app/actions")} className="inline-flex items-center gap-1 text-xs font-bold text-[#17201e]">Review ranked opportunities <ChevronRight className="h-3.5 w-3.5" /></button></div> : <p className="mt-3 text-sm leading-6 text-[#65706b]">No verified opportunities yet. Cresna will wait for enough connected-store evidence.</p>}<button type="button" onClick={() => setLocation("/app/ai-studio")} className="mt-5 inline-flex items-center gap-2 text-xs font-bold text-[#17201e]"><Sparkles className="h-3.5 w-3.5 text-[#7c9b1e]" />Open AI Action Studio</button></section>
        <section className="rounded-[1.35rem] border border-[#17201e]/12 bg-[#fdfdfb] p-6"><div className="flex gap-3"><ShieldCheck className="h-5 w-5 shrink-0 text-[#7c9b1e]" /><div><p className="text-sm font-bold">You approve every change.</p><p className="mt-1 text-xs leading-5 text-[#65706b]">Cresna creates reviewable drafts, records your decision, and never changes Shopify automatically.</p></div></div></section>
      </aside>
    </div>}
  </WorkspaceFrame>;
}
