import { Check, CircleAlert, CreditCard, LockKeyhole } from "lucide-react";

type RevenueCatPaywallProps = {
  packageLinked?: boolean;
};

const plans = [
  { name: "Free", price: "$0", actions: "10 AI actions / month", detail: "A real workspace to explore Cresna with a deliberately limited action allowance.", features: ["Connect permitted Shopify read data", "Growth Profile and evidence baseline", "Visible path to upgrade"], packageId: undefined, featured: false },
  { name: "Pro", price: "$19", actions: "500 AI actions / month", detail: "For independent owners who need a disciplined evidence-to-action workflow.", features: ["Evidence-backed opportunity ranking", "Merchant-reviewed AI product and positioning drafts", "Outcome tracking and approved write-intent records"], packageId: "cresna_pro_monthly", featured: false },
  { name: "Growth", price: "$49", actions: "2,500 AI actions / month", detail: "For growing brands that need more room to turn store evidence into measured improvements.", features: ["Everything in Pro", "Five times the Pro action allowance", "Deeper connected catalog intelligence"], packageId: "cresna_growth_monthly", featured: true },
] as const;

export function RevenueCatPaywall({ packageLinked = false }: RevenueCatPaywallProps) {
  return <section className="mt-7 overflow-hidden rounded-[1.4rem] border border-border bg-card text-card-foreground">
    <div className="border-b border-border px-6 py-6 sm:px-7"><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2"><CreditCard className="h-4 w-4 text-primary" /><p className="eyebrow text-[10px] text-muted-foreground">RevenueCat paywall contract</p></div><h2 className="mt-3 text-xl font-extrabold tracking-[-0.05em]">The Cresna upgrade experience is ready for linked packages.</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">Offering: <code className="rounded bg-secondary px-1.5 py-0.5 text-[11px] font-bold text-secondary-foreground">cresna_default</code>. This source surface is intentionally honest: it does not present RevenueCat checkout as active until Stripe Web Billing products and RevenueCat packages are linked.</p></div><span className={`inline-flex items-center gap-1.5 rounded-full px-3 py-1.5 text-[10px] font-bold ${packageLinked ? "bg-primary text-primary-foreground" : "bg-secondary text-secondary-foreground"}`}>{packageLinked ? <Check className="h-3.5 w-3.5" /> : <LockKeyhole className="h-3.5 w-3.5" />}{packageLinked ? "Packages linked" : "Packages not linked"}</span></div></div>
    <div className="grid gap-px bg-border lg:grid-cols-3">{plans.map(plan => <article key={plan.name} className={`p-6 sm:p-7 ${plan.featured ? "bg-[#17201e] text-[#f8f7f2]" : "bg-card text-card-foreground"}`}><p className={`eyebrow text-[10px] ${plan.featured ? "text-[#d9fa55]" : "text-muted-foreground"}`}>{plan.name}</p><p className="mt-5 text-4xl font-extrabold tracking-[-0.07em]">{plan.price}<span className={`ml-1 text-xs font-medium tracking-normal ${plan.featured ? "text-[#b6c1bb]" : "text-muted-foreground"}`}>/ month</span></p><p className={`mt-2 text-xs font-bold ${plan.featured ? "text-[#d9fa55]" : "text-primary"}`}>{plan.actions}</p><p className={`mt-5 text-sm leading-6 ${plan.featured ? "text-[#d9e1dc]" : "text-muted-foreground"}`}>{plan.detail}</p><ul className="mt-6 space-y-3">{plan.features.map(feature => <li key={feature} className={`flex gap-2 text-xs leading-5 ${plan.featured ? "text-[#d9e1dc]" : "text-muted-foreground"}`}><Check className={`mt-0.5 h-4 w-4 shrink-0 ${plan.featured ? "text-[#d9fa55]" : "text-primary"}`} />{feature}</li>)}</ul>{plan.packageId ? <div className={`mt-6 rounded-xl p-3 text-[10px] leading-5 ${plan.featured ? "bg-white/10 text-[#d9e1dc]" : "bg-secondary text-secondary-foreground"}`}><span className="font-bold">Prepared package:</span> <code>{plan.packageId}</code></div> : <div className={`mt-6 rounded-xl p-3 text-[10px] leading-5 ${plan.featured ? "bg-white/10 text-[#d9e1dc]" : "bg-secondary text-secondary-foreground"}`}>No payment method or trial is required for Cresna Free.</div>}</article>)}</div>
    {!packageLinked ? <div className="flex items-start gap-3 border-t border-border bg-primary/10 px-6 py-4 text-xs leading-5 text-foreground sm:px-7"><CircleAlert className="mt-0.5 h-4 w-4 shrink-0 text-primary" /><p><strong>Activation still required.</strong> Link Stripe Web Billing products to the Pro and Growth packages in RevenueCat, then test the full purchase and webhook path before enabling this paywall for customers. Cresna’s secure webhook endpoint remains part of the source package.</p></div> : null}
  </section>;
}
